let a=document.createElement("div")
document.body.appendChild(a)
a.setAttribute("id","container")

let b=document.createElement("h1")
b.setAttribute("id","h1")
a.appendChild(b)
let HeadEL=document.createTextNode("LOGIN PAGE")
b.appendChild(HeadEL)
let c=document.createElement("input")
document.body.appendChild(c)
let d=document.createElement("input")
d.setAttribute("type","button")
d.setAttribute("value","submit")
document.body.appendChild(d)